script cleanup

diff --git a/array_submitter_sweeper b/array_submitter_sweeper
--- a/array_submitter_sweeper
+++ b/array_submitter_sweeper
@@ -18,14 +18,14 @@ elif [[ "$(hostname)" == *"cedar"* ]] || [[ "$(hostname)" == *"gra"* ]]; then
 fi
 
 # general settings
-PROJECT_DIR="PROJECT_NAME" # project name
-EXP_NAME="EXP_NAME" # experiment name used by e.g. sacred
-CPUS_PER_TASK=6 # should be no more than 6 per GPU! -- SEE COMPUTE CANADA
+PROJECT_DIR="tri-density-matching" # project name
+EXP_NAME="maps-sweeper"
+CPUS_PER_TASK=6
 ACCOUNT='rrg-kevinlb' # def-fwood or rrg-kevinlb
 REPEATS=1
-TAG="TAG" # wandb tags
-TIME="23:59:00" # <HH:MM:SS>
-GPUS=1
+MEM="32G" # G/M is Gigabyte/Megabyte
+TIME="0-12:00:00" # <DD-HH:MM:SS>
+GPUS=1 # set to 0 to not ask for any
 # PLAI specific arguments - partition (plai/plai_towers/plai_cpus)
 PARTITION="plai"
 
@@ -38,58 +38,22 @@ CONTAINER_NAME="container.sif"
 # LEAVE EMPTY SO THAT WE DO NOT COPY ANYTHING TO SLURM_TMPDIR
 STUFF_TO_TMP=""
 
-# command send to container
-CMD_BASE=""
-
-function array_to_pearl () {
-    echo "($(echo "$1" | sed 's/ /, /g'))"
-}
-
-function geometric {
-    ((val = $1))
-    ((mult = $2))
-    ((count = $3))
-
-    tmp="$val"
-    while [[ ${count} -gt 0 ]] ; do
-        ((val *= mult))
-        ((count -= 1))
-        tmp="${tmp}, ${val}"
-    done
-    echo $tmp
-}
-
-# specify options over which to sweep (for instance batch_size)
-example1=$(geometric 1 2 10)
-example2="($(seq -s ', ' 1 20))"
-example3="($(seq -s ', ' 25 25 1000))"
-
-# EXTEND FOR LOOP WITH MORE OPTIONS
-OPTIONS="$(perl -le '@ex1 = '"$(array_to_pearl "${example1}")"';
-                        @ex2 ='"$(array_to_pearl "${example2}")"';
-                        @ex3 ='"$(array_to_pearl "${example3}")"';
-                        for my $i (0 .. $#hd){
-                            print "ex1=$ex1[int($i/4)] ".
-                            "ex2=$ex2[int($i/2)] ".
-                            "ex3=$ex3[int($i)]"
-                            }')"
-
-
-# create array which splits string on \n from above
-# readarray -t OPTIONS <<< $OPTIONS # ONLY BASH 4.4+
-IFS=$'\n' read -rd '' -a OPTIONS <<<"$OPTIONS"
-N=${#OPTIONS[@]}
+# wandb sweeper id and number of sweeps
+CMD_BASE="wandb agent --count 1 ${wandb-sweeper-id}"
+SWEEPERID=""
+N=1
 
 # clear array_command_list.txt before putting thins into it
 array_commands="array_command_list_${EXP_NAME}.txt"
 > "${array_commands}"
-for option in "${OPTIONS[@]}"; do
-    echo "${CMD_BASE} ${option}" >> "${array_commands}"
+for i in $(seq $N); do
+    echo "${CMD_BASE}" >> "${array_commands}"
 done
 
 # Directory where this script is called
 DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" >/dev/null 2>&1 && pwd )"
-EXP_DIR="$(dirname "$DIR")" # get parent of parent directory from where this script is called (assumes submitted from exp_dir/hpc_scripts/some_dir)
+
+EXP_DIR="$(dirname "$DIR")" # get parent of parent directory from where this script is called (assumes submitted from exp_dir/hpc_scripts)
 
 # set base directory names to store results from jobs (specific directory will be given in the job script)
 if [ ! -z ${SCRATCH} ]; then
@@ -101,13 +65,15 @@ if [ ! -z ${SCRATCH} ]; then
         mkdir -p "${BASEDIR}/${EXP_NAME}/hpc_output"
     fi
 
+    if [ ! -d "${BASEDIR}/${EXP_NAME}/results" ]; then
+        mkdir -p "${BASEDIR}/${EXP_NAME}/results"
+    fi
+
     VARIABLES="CODE_DIR=${EXP_DIR},WORKDIR_MOUNT=${WORKDIR_MOUNT},\
 CONTAINER=${CONTAINER_NAME},RESULTS_MOUNT=${RESULTS_MOUNT},\
-STUFF_TO_TMP=${STUFF_TO_TMP},BASEDIR=${BASEDIR}"
+STUFF_TO_TMP=${STUFF_TO_TMP}, BASEDIR=${BASEDIR}"
 
     # SUBMIT JOBS
-    CMD_N="${CMD_BASE_N}"
-
     sbatch_cmd="--job-name=${EXP_NAME} \
                 --time=${TIME} \
                 --cpus-per-task=${CPUS_PER_TASK} \
@@ -116,7 +82,7 @@ STUFF_TO_TMP=${STUFF_TO_TMP},BASEDIR=${BASEDIR}"
                 --mem=${MEM} \
                 --chdir=${BASEDIR} \
                 -o ${BASEDIR}/${EXP_NAME}/hpc_output/${EXP_NAME}_%A_%a.out \
-                --export=ALL,\"${VARIABLES}\",EXP_NAME=${EXP_NAME}"
+                --export=ALL,CMD=\"${CMD_N}\",\"${VARIABLES}\",EXP_NAME=${EXP_NAME}"
 
     re='^[0-9]+$'
     if  [[ ! $GPUS =~ $re ]] ; then
@@ -127,17 +93,22 @@ STUFF_TO_TMP=${STUFF_TO_TMP},BASEDIR=${BASEDIR}"
                 sbatch_cmd="${sbatch_cmd} --gres=gpu:${GPUS}"
             fi
             sbatch_cmd="${sbatch_cmd} --array=1-${N}%10 --partition=${PARTITION}"
-            bash -c "sbatch ${sbatch_cmd[@]} ~/hpc/plai_array_job.sh"
+            for _ in $(seq $REPEATS); do
+                bash -c "sbatch ${sbatch_cmd[@]} ~/hpc/plai_array_job.sh"
+                sleep 1
+            done
         elif [[ "$CLUSTER" = "CC" ]]; then
             if [[ "$GPUS" != "0" ]]; then
                 sbatch_cmd="${sbatch_cmd} --gres=gpu:v100l:${GPUS}"
-                #sbatch_cmd="${sbatch_cmd} --gres=gpu:${GPUS}"
             fi
-            sbatch_cmd="${sbatch_cmd} --array=1-${N} --account=${ACCOUNT}"
-            bash -c "sbatch ${sbatch_cmd[@]} ~/hpc/cc_array_job.sh"
+            sbatch_cmd="${sbatch_cmd} --account=${ACCOUNT} --array=1-${N}"
+            for _ in $(seq $REPEATS); do
+                bash -c "sbatch ${sbatch_cmd[@]} ~/hpc/cc_array_job.sh"
+                sleep 1
+            done
         fi
         sleep 1 # sleep so that we do not overwhelm the scheduler (SEE e.g. compute canada's website)
     fi
 else
-    echo "error while submitting job" >&2; exit 1
+    echo "error while submitting job (maybe you aren't on an hpc?)" >&2; exit 1
 fi
