fix jobsubmitters

diff --git a/array_submitter b/array_submitter
--- a/array_submitter
+++ b/array_submitter
@@ -111,41 +111,38 @@ CONTAINER=${CONTAINER_NAME},RESULTS_MOUNT=${RESULTS_MOUNT},\
 STUFF_TO_TAR=${STUFF_TO_TAR},BASERESULTSDIR=${BASERESULTSDIR}"
 
     # SUBMIT JOBS
-    for CMD_BASE_N in "${CMDs[@]}"
-    do
-        CMD_N="${CMD_BASE_N}"
+    CMD_N="${CMD_BASE_N}"
 
-        sbatch_cmd="--job-name=${EXP_NAME} \
-                   --time=${TIME} \
-                   --cpus-per-task=${CPUS_PER_TASK} \
-                   --ntasks-per-core=1 \
-                   --ntasks=1 \
-                   --array=1-${N}%20 \
-                   --mem=${MEM} \
-                   --chdir=${BASERESULTSDIR} \
-                   -o ${BASERESULTSDIR}/hpc_output/${EXP_NAME}_%j.out \
-                   --export=ALL,CMD=\"${CMD_N}\",\"${VARIABLES}\",EXP_NAME=${EXP_NAME}"
+    sbatch_cmd="--job-name=${EXP_NAME} \
+                --time=${TIME} \
+                --cpus-per-task=${CPUS_PER_TASK} \
+                --ntasks-per-core=1 \
+                --ntasks=1 \
+                --array=1-${N}%20 \
+                --mem=${MEM} \
+                --chdir=${BASERESULTSDIR} \
+                -o ${BASERESULTSDIR}/hpc_output/${EXP_NAME}_%j.out \
+                --export=ALL,\"${VARIABLES}\",EXP_NAME=${EXP_NAME}"
 
-        re='^[0-9]+$'
-        if ! [[ $GPUS =~ $re ]] ; then
-            echo "error: GPUS must be interger" >&2; exit 1
-        else
-            if [[ "$CLUSTER" = "PLAI" ]]; then
-                if [[ "$GPUS" != "0" ]]; then
-                    sbatch_cmd="${sbatch_cmd} --gres=gpu:${GPUS}"
-                fi
-                sbatch_cmd="${sbatch_cmd} --partition=${PARTITION}"
-                bash -c "sbatch ${sbatch_cmd[@]} ~/hpc/plai_array_job.sh"
-            elif [[ "$CLUSTER" = "CC" ]]; then
-                if [[ "$GPUS" != "0" ]]; then
-                    sbatch_cmd="${sbatch_cmd} --gres=gpu:${GPUS}"
-                    #sbatch_cmd="${sbatch_cmd} --gres=gpu:${GPUS}"
-                fi
-                bash -c "sbatch ${sbatch_cmd[@]} ~/hpc/cc_array_job.sh"
+    re='^[0-9]+$'
+    if  [[ ! $GPUS =~ $re ]] ; then
+        echo "error: GPUS must be interger" >&2; exit 1
+    else
+        if [[ "$CLUSTER" = "PLAI" ]]; then
+            if [[ "$GPUS" != "0" ]]; then
+                sbatch_cmd="${sbatch_cmd} --gres=gpu:${GPUS}"
             fi
-            sleep 1 # sleep so that we do not overwhelm the scheduler (SEE e.g. compute canada's website)
+            sbatch_cmd="${sbatch_cmd} --partition=${PARTITION}"
+            bash -c "sbatch ${sbatch_cmd[@]} ~/hpc/plai_array_job.sh"
+        elif [[ "$CLUSTER" = "CC" ]]; then
+            if [[ "$GPUS" != "0" ]]; then
+                sbatch_cmd="${sbatch_cmd} --gres=gpu:${GPUS}"
+                #sbatch_cmd="${sbatch_cmd} --gres=gpu:${GPUS}"
+            fi
+            bash -c "sbatch ${sbatch_cmd[@]} ~/hpc/cc_array_job.sh"
         fi
-    done
+        sleep 1 # sleep so that we do not overwhelm the scheduler (SEE e.g. compute canada's website)
+    fi
 else
     echo "error while submitting job" >&2; exit 1
 fi
