enable sweeping

diff --git a/job_submitter_single_task b/job_submitter_single_task
--- a/job_submitter_single_task
+++ b/job_submitter_single_task
@@ -14,15 +14,10 @@
 PROJECT_DIR="PN" # project name
 EXP_NAME="TEST"
 USE_MONGO="FALSE"
-N=1 # number of times to submit
-# set seed; should only be done if N=1 (otherwise each job gets same seed variable)
-if [ "$N" -eq "1" ]
-    seed=""
-fi
 CPUS_PER_TASK=1 # should be no more than 6 per GPU! -- SEE COMPUTE CANADA
 MEM="5G" # G/M is Gigabyte/Megabyte
 TIME="01:00:00" # <HH:MM:MM>
-GPUS=1
+GPUS=1 # set to 0 to not ask for any
 CLUSTER="PLAI" # CC/PLAI
 # PLAI specific arguments - partition (plai/plai_towers/plai_cpus)
 PARTITION="plai"
@@ -36,6 +31,39 @@ CONTAINER_NAME="raven.sif"
 
 # command send to container
 CMD_BASE=""
+
+# sweeping
+DOSWEEP=true
+
+if [[ $DOSWEEP = true ]]; then
+    function array_to_pearl () {
+        echo "($(echo "$1" | sed 's/ /, /g'))"
+    }
+
+    CMDs=()
+    # specify options over which to sweep (for instance batch_size)
+    batch_size="64"
+
+    # EXTEND FOR LOOP WITH MORE OPTIONS
+    OPTIONS="$(perl -le '@batch_size = '"$(array_to_pearl "${batch_size}")"';
+                     for $b (@batch_size){
+                         print "batch_size=$b"}')"
+    # create array which splits string on \n from above
+    readarray -t OPTIONS <<< $OPTIONS
+    for option in "${OPTIONS[@]}"; do
+        tmp="${CMD_BASE} ${option}"
+        CMDs+=("$tmp")
+    done
+else
+    CMDs=($CMD_BASE)
+fi
+
+# number of times to submit
+N=${#CMDs[@]}
+# set seed; should only be done if N=1 (otherwise each job gets same seed variable)
+if [ "$N" -eq "1" ]; then
+    seed=""
+fi
 
 # Directory where this script is called
 DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" >/dev/null 2>&1 && pwd )"
@@ -69,14 +97,14 @@ STUFF_TO_TAR=${STUFF_TO_TAR},RESULTS_TO_TAR=${RESULTS_TO_TAR},BASERESULTSDIR=${B
     rsync -av "${EXP_DIR}/${CONTAINER_NAME}" "${BASERESULTSDIR}"
 
     # SUBMIT JOBS
-    for n in $(seq 1 $N)
+    for CMD_BASE_N in "${CMDs[@]}"
     do
 
         if [ ! -z ${seed} ]; then
             # if seed is not set make one
             seed=$(python -c "import random; print random.randint(0,2**32-1)")
         fi
-        CMD_N="${CMD_BASE} seed=${seed}"
+        CMD_N="${CMD_BASE_N} seed=${seed}"
 
         sbatch_cmd = "--job-name=${EXP_NAME} \
                    --time=${TIME} \
@@ -84,10 +112,18 @@ STUFF_TO_TAR=${STUFF_TO_TAR},RESULTS_TO_TAR=${RESULTS_TO_TAR},BASERESULTSDIR=${B
                    --ntasks-per-core=1 \
                    --ntasks=1 \
                    --mem=${MEM} \
-                   --gres=gpu:${GPUS} \
                    --chdir=${BASERESULTSDIR} \
                    -o ${BASERESULTSDIR}/hpc_output/${EXP_NAME}_%j.out \
                    --export=ALL,CMD=${CMD_N},${VARIABLES},EXP_NAME=${EXP_NAME},USE_MONGO=${USE_MONGO}"
+
+        re='^[0-9]+$'
+        if ! [[ "$GPUS" =~ "$re" ]] ; then
+            echo "error: GPUS must be interger" >&2; exit 1
+        else
+            if [[ "$GPUS" = "0" ]]; then
+                sbatch_cmd = "${sbatch_cmd} --gres=gpu:${GPUS}"
+            fi
+        fi
 
         if [[ "$CLUSTER" = "PLAI" ]]; then
                 sbatch_cmd="${sbatch_cmd} \
@@ -104,5 +140,5 @@ STUFF_TO_TAR=${STUFF_TO_TAR},RESULTS_TO_TAR=${RESULTS_TO_TAR},BASERESULTSDIR=${B
         sleep 1 # sleep so that we do not overwhelm the scheduler (SEE e.g. compute canada's website)
     done
 else
-    exit 1
+    echo "error while submitting job" >&2; exit 1
 fi
